#!/bin/bash
echo "安装sublime text 2.0.2..."
sudo add-apt-repository ppa:webupd8team/sublime-text-2 -y
sudo apt-get update
sudo apt-get install sublime-text -y

echo "fcitx中文输入法补丁..."
sudo apt-get install build-essential
sudo apt-get install libgtk2.0-dev
gcc -shared -o libsublime-imfix.so imfix.c  `pkg-config --libs --cflags gtk+-2.0` -fPIC
sudo cp libsublime-imfix.so /opt/sublime_text_2/
[ -f "/usr/bin/subl" ] && \
sudo rm /usr/bin/subl
sudo cp subl /usr/bin/


echo -n "汉化主界面?[Y/n]?"
read ans
case "$ans" in  n*|N*)
    echo -n "安装完成...按[ENTER]键继续..."
    read w
    exit 1;
esac     
packpath='/opt/sublime_text_2/Pristine Packages'
[ -f "$packpath"/backupDefault ] && \
sudo rm "$packpath"/backupDefault
[ -f "$packpath"/Default.sublime-package ] && \
sudo mv "$packpath"/Default.sublime-package "$packpath"/backupDefault
sudo cp Default.sublime-package "$packpath"/

echo -n "安装完成...按[ENTER]键继续..."
read w


